// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zkdeznpqryfqrqxiyypk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InprZGV6bnBxcnlmcXJxeGl5eXBrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NzQ2NzksImV4cCI6MjA2ODU1MDY3OX0.mDqW-KU5UTwK4FkI-kUYUn49gcKLE2ZqcrUSjCPefW0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);